services:

  s1r1:
    image: clickhouse/clickhouse-server:latest
    container_name: s1r1
    hostname: s1r1
    environment:
      - CLICKHOUSE_PASSWORD=click123
    volumes:
      - ./config/clickhouse/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      - ./config/clickhouse/s1r1_macros.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./config/keeper/keeper1.xml:/etc/clickhouse-server/config.d/keeper.xml
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9181:9181"

  s1r2:
    image: clickhouse/clickhouse-server:latest
    container_name: s1r2
    hostname: s1r2
    environment:
      - CLICKHOUSE_PASSWORD=click123
    volumes:
      - ./config/clickhouse/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      - ./config/clickhouse/s1r2_macros.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./config/keeper/keeper2.xml:/etc/clickhouse-server/config.d/keeper.xml
    ports:
      - "8124:8123"
      - "9001:9000"
      - "9182:9181"

  s2r1:
    image: clickhouse/clickhouse-server:latest
    container_name: s2r1
    hostname: s2r1
    environment:
      - CLICKHOUSE_PASSWORD=click123
    volumes:
      - ./config/clickhouse/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      - ./config/clickhouse/s2r1_macros.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./config/keeper/keeper3.xml:/etc/clickhouse-server/config.d/keeper.xml
    ports:
      - "8125:8123"
      - "9002:9000"
      - "9183:9181"

  s2r2:
    image: clickhouse/clickhouse-server:latest
    container_name: s2r2
    hostname: s2r2
    environment:
      - CLICKHOUSE_PASSWORD=click123
    volumes:
      - ./config/clickhouse/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      - ./config/clickhouse/s2r2_macros.xml:/etc/clickhouse-server/config.d/macros.xml
    ports:
      - "8126:8123"
      - "9003:9000"
