services:
  manticore:
    image: manticoresearch/manticore:latest
    container_name: manticore
    ports:
      - "9306:9306"
      - "9308:9308"
    environment:
      - MANTICORE_CONFIG=/etc/manticoresearch/manticore.conf
    volumes:
      - ./config/manticore.conf:/etc/manticoresearch/manticore.conf
